### PR TITLE
First draft completed disability-daily-activities

### PR DESCRIPTION
**Pull request by CatReid**
First draft completed disability-daily-activities, styled and rendered. data.R and metadata completed.

### CODE REVIEW

**Review by MikeJohnPage — CHANGES_REQUESTED** [review]
Unfortunately, you can't sum the percentages across groups like you have done. Imagine you have two groups, each with 50% meeting the criteria, you couldn't sum the percentages to conclude that 100% of the residents meet the criteria. You could instead calculate the mean across the groups using `rowwise()` in combination with `mean()` (see [here](https://dplyr.tidyverse.org/articles/rowwise.html) for why you need `rowwise()`), but this also isn't quite what you want.

Rather than calculate the mean across _groups_, you want to calculate the mean across the _sample_ (who happen to fall into the groups). To do this I would:
- reimport the Excel spreadsheet, using the counts, rather than percentage table (sheet range A9:V20).
- Sum up the population meeting the criteria across the age brackets you are interested in
- Sum up the total population across the age brackets you are interested in
- divie the people meeting the criteria by the total population, for each area

Does that make sense? Happy to do a deep diver if not.

**Review by CatReid — COMMENTED** [review]
Completed corrections

**Comment by MikeJohnPage** [comment]
Unfortunately, the new method also isn't quite right (but it's close!).

I've pushed two commits to your branch. Please look at the changes I made to understand why your second approach didn't work:

- You can't sum across rows using `+` like you have done. Doing this sums across columns. You need to call `rowwise()` first to perform operations across rows.
- `sum()` should be used for adding, rather than `+`. It is more idiomatic.

**Comment by MikeJohnPage** [comment]
I'm going to merge and close now - happy to jump on a call to run through the changes I made in more detail if helpful.

**Pull request merged**
